# Generated by Django 6.0.5 on 2026-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('guidelines', 'Guidelines'), ('orders', 'Orders'), ('templates', 'Templates'), ('reports', 'Reports'), ('tenders', 'Tenders'), ('circulars', 'Circulars'), ('notifications', 'Notifications')], default='guidelines', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, help_text='Upload the actual document (PDF, DOCX, etc.)', null=True, upload_to='documents/')),
                ('external_url', models.URLField(blank=True, help_text='If document is hosted externally, paste URL here instead of uploading')),
                ('file_size_display', models.CharField(blank=True, help_text="e.g. '2.4 MB'", max_length=20)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['order', '-publish_date', '-created_at'],
            },
        ),
    ]
