# Generated by Django 6.0.5 on 2026-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker', models.CharField(default='About Us', max_length=100)),
                ('hero_title', models.CharField(default='Empowering Digital Governance for a Smarter Puducherry', max_length=300)),
                ('hero_description', models.TextField(default='The Directorate of Information Technology (DIT), Government of Puducherry, serves as the central agency driving digital transformation and e-Governance initiatives across the Union Territory.')),
                ('intro_para1', models.TextField(default='Established with the vision of creating a technologically empowered administration...', verbose_name='Introduction Paragraph 1')),
                ('intro_para2', models.TextField(blank=True, verbose_name='Introduction Paragraph 2')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_text', models.TextField(default='To build a digitally connected, transparent, and technology-driven Puducherry...')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('citizen_services_title', models.CharField(default='Citizen-Centric Digital Services', max_length=200)),
                ('citizen_services_text', models.TextField(default='DIT is committed to simplifying access to Government services...')),
                ('innovation_title', models.CharField(default='Driving Innovation & Digital Transformation', max_length=200)),
                ('innovation_para1', models.TextField(default='As technology continues to evolve, the Directorate actively explores innovative solutions...')),
                ('innovation_para2', models.TextField(blank=True)),
                ('commitment_title', models.CharField(default='Commitment to Excellence', max_length=200)),
                ('commitment_text', models.TextField(default='The Directorate of Information Technology remains dedicated to delivering reliable, transparent, and efficient digital governance solutions...')),
                ('commitment_tagline', models.CharField(default='Together, we are building a smarter, digitally empowered Puducherry.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='InitiativeFocusPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. "Online public service delivery"', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Initiative Focus Point',
                'verbose_name_plural': 'Initiative Focus Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='One key function line, e.g. "Implementation of e-Governance projects..."')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Key Function',
                'verbose_name_plural': 'Key Functions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='One mission bullet point, e.g. "To promote effective adoption of IT..."')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mission Point',
                'verbose_name_plural': 'Mission Points',
                'ordering': ['order'],
            },
        ),
    ]
