# Generated by Django 6.0.5 on 2026-06-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='site',
            field=models.OneToOneField(blank=True, help_text='The website this About page belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboutpage', to='sites.site'),
        ),
        migrations.AddField(
            model_name='initiativefocuspoint',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='keyfunction',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='missionpoint',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
    ]
