# Generated by Django 6.0.5 on 2026-06-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_alter_site_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAccessButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Button text, e.g. 'Teacher Login'", max_length=100)),
                ('href', models.CharField(default='#', help_text="Internal path or anchor, e.g. '/login?role=teacher'", max_length=300)),
                ('icon', models.CharField(choices=[('UserRoundCheck', 'Teacher / User'), ('Shuffle', 'Transfer / Shuffle'), ('TicketCheck', 'Vacancy / Ticket'), ('Bell', 'Notifications'), ('Download', 'Downloads'), ('Headphones', 'Helpdesk'), ('FileText', 'Documents'), ('Home', 'Home')], default='FileText', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Quick Access Button',
                'verbose_name_plural': 'Quick Access Buttons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TransferRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Transfer Counselling Round 1 – 2026'", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Brief note shown to teachers')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active / Open'), ('closed', 'Closed')], default='upcoming', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Transfer Round',
                'verbose_name_plural': 'Transfer Rounds',
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
