# Generated by Django 6.0.5 on 2026-06-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_content', '0001_initial'),
        ('sites', '0003_alter_site_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickaccessbutton',
            name='href',
            field=models.CharField(default='#', help_text="Internal path, e.g. '/login?role=teacher' or '/#vacancy-list'", max_length=300),
        ),
        migrations.AlterField(
            model_name='quickaccessbutton',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferround',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferround',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='EduCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Pending Applications'", max_length=100)),
                ('value', models.CharField(help_text="e.g. '14', 'Live', '95%'", max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Teacher Counter',
                'verbose_name_plural': 'Teacher Counters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EduFooterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="Column heading, e.g. 'Teacher Services'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Footer Link Group',
                'verbose_name_plural': 'Footer Link Groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EduFooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('href', models.CharField(default='/', help_text="React Router path or anchor, e.g. '/#vacancy-list'", max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='edu_content.edufootergroup')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EduGrievanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Resolution Rate'", max_length=100)),
                ('value', models.CharField(help_text="e.g. '95%'", max_length=30)),
                ('helper', models.CharField(blank=True, help_text='Small caption below the value', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Grievance Stat',
                'verbose_name_plural': 'Grievance Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EduTrustPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="e.g. 'Acknowledgement number issued instantly'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Grievance Trust Point',
                'verbose_name_plural': 'Grievance Trust Points',
                'ordering': ['order'],
            },
        ),
    ]
