# Generated by Django 6.0.5 on 2026-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated, or enter manually)', max_length=300, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('event', 'Event'), ('press_release', 'Press Release')], default='general', max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Short preview text shown in news cards', max_length=500)),
                ('body', models.TextField(help_text='Full article content (HTML or plain text)')),
                ('image', models.ImageField(blank=True, help_text='Optional featured image for this article', null=True, upload_to='news/images/')),
                ('publish_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsTickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Short news line (e.g. 'Purchase and AMC Guidelines issued on 11 Feb 2024')", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this item without deleting it')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first in ticker')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Ticker Item',
                'verbose_name_plural': 'News Ticker Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
