# Generated by Django 6.0.5 on 2026-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(help_text="Small label above title, e.g. 'DIRECTORATE OF IT'", max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(help_text='Large banner image (recommended: 1920x600px)', upload_to='hero_banners/')),
                ('primary_cta_label', models.CharField(blank=True, max_length=100, verbose_name='Primary Button Text')),
                ('primary_cta_href', models.CharField(blank=True, default='#services', max_length=200)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=100, verbose_name='Secondary Button Text')),
                ('secondary_cta_href', models.CharField(blank=True, max_length=200)),
                ('variant', models.CharField(choices=[('danger', 'Red (Danger)'), ('primary', 'Blue (Primary)'), ('success', 'Green (Success)'), ('dark', 'Dark')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order'],
            },
        ),
    ]
