# Generated by Django 6.0.5 on 2026-06-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_banner', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order'], 'verbose_name': 'Hero Banner Slide', 'verbose_name_plural': 'Hero Banner Slides'},
        ),
        migrations.AddField(
            model_name='herobanner',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(help_text='Large banner image (recommended: 1920×600 px)', upload_to='hero_banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (0 = first slide)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='primary_cta_label',
            field=models.CharField(blank=True, help_text='e.g. "Explore Services"', max_length=100, verbose_name='Primary Button Text'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='secondary_cta_label',
            field=models.CharField(blank=True, help_text='e.g. "Learn More" — leave blank to hide', max_length=100, verbose_name='Secondary Button Text'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='variant',
            field=models.CharField(choices=[('danger', 'Red (Danger)'), ('primary', 'Blue (Primary)'), ('success', 'Green (Success)'), ('dark', 'Dark')], default='danger', max_length=20),
        ),
    ]
