# Generated by Django 6.0.5 on 2026-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('circular', 'Circular'), ('advisory', 'Advisory'), ('announcement', 'Announcement'), ('workshop', 'Workshop'), ('update', 'System Update')], default='announcement', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF or document attachment', null=True, upload_to='notifications/attachments/')),
                ('publish_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important/urgent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
