# Generated by Django 6.0.5 on 2026-05-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('network', 'Network'), ('server', 'Server'), ('users', 'Users'), ('portal', 'Portal'), ('shield', 'Shield'), ('training', 'Training'), ('laptop', 'Laptop'), ('cloud', 'Cloud')], default='laptop', max_length=50)),
                ('accent_color', models.CharField(default='#3B82F6', help_text='Hex color, e.g. #3B82F6', max_length=20)),
                ('surface_color', models.CharField(default='rgba(59,130,246,0.12)', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(default='#services-detail', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
