# Generated by Django 6.0.5 on 2026-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicelink',
            options={'ordering': ['order'], 'verbose_name': 'Service Link', 'verbose_name_plural': 'Service Links'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='accent_color',
            field=models.CharField(default='#3B82F6', help_text='Hex colour e.g. #3B82F6', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('network', 'Network (PSWAN)'), ('server', 'Server (SDC)'), ('users', 'Users (CSC)'), ('portal', 'Portal'), ('shield', 'Shield (Cybersecurity)'), ('training', 'Training'), ('laptop', 'Laptop'), ('cloud', 'Cloud'), ('database', 'Database'), ('mobile', 'Mobile'), ('wifi', 'WiFi'), ('lock', 'Lock / Security')], default='laptop', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (0 = first card)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='surface_color',
            field=models.CharField(default='rgba(59,130,246,0.12)', help_text='RGBA colour for background', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicelink',
            name='href',
            field=models.CharField(default='#services-detail', help_text='Link target, e.g. "#contact"', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicelink',
            name='label',
            field=models.CharField(help_text='Button text, e.g. "Learn More"', max_length=100),
        ),
    ]
