# Generated by Django 6.0.5 on 2026-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Shri. K. Lakshminarayanan'", max_length=200)),
                ('role', models.CharField(help_text='e.g. "Hon\'ble Minister for Information Technology"', max_length=250)),
                ('photo', models.ImageField(blank=True, help_text='Square portrait photo (recommended 300×300px). Leave blank to show initials.', null=True, upload_to='officials/')),
                ('initials', models.CharField(blank=True, help_text="Shown if no photo is uploaded, e.g. 'KL'", max_length=5)),
                ('email', models.EmailField(blank=True, help_text='Optional contact email for this office', max_length=254)),
                ('order', models.PositiveIntegerField(default=0, help_text='0 = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership / Official',
                'verbose_name_plural': 'Leadership & Officials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name, e.g. 'Digital India'", max_length=200)),
                ('wordmark', models.CharField(blank=True, help_text="Short label shown under logo, e.g. 'Digital India'", max_length=100)),
                ('initials', models.CharField(blank=True, help_text="Fallback text if logo image fails, e.g. 'DI'", max_length=5)),
                ('logo', models.ImageField(blank=True, help_text='Upload a logo image (preferred)', null=True, upload_to='partners/')),
                ('logo_url', models.URLField(blank=True, help_text='OR paste an external logo image URL instead of uploading')),
                ('logo_alt', models.CharField(blank=True, help_text='Accessibility alt text for the logo', max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(default='#', help_text='Where the card links to (full https:// URL)', max_length=300)),
                ('tone', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('emerald', 'Emerald / Green')], default='blue', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Connected Platform',
                'verbose_name_plural': 'Connected Platforms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g. '24x7', '6', '1'", max_length=30)),
                ('label', models.CharField(help_text="e.g. 'Digital access'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'verbose_name_plural': 'Hero Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(choices=[('laptop', 'Laptop'), ('fileInvoice', 'File / Invoice'), ('bullhorn', 'Bullhorn / Announce'), ('download', 'Download')], default='laptop', max_length=30)),
                ('href', models.CharField(default='#', max_length=200)),
                ('accent', models.CharField(default='#3B82F6', max_length=20)),
                ('surface', models.CharField(default='rgba(59,130,246,0.12)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='Directorate of Information Technology', max_length=200)),
                ('government_name', models.CharField(default='Government of Puducherry', max_length=200)),
                ('helpdesk_email', models.EmailField(default='directorit@py.gov.in', max_length=254)),
                ('phone', models.CharField(default='+91-413-2246090', max_length=50)),
                ('address', models.TextField(default='II Floor, Planning & Research Department Complex, 505, Kamaraj Salai, Sakthi Nagar, Saram, Puducherry, 605013')),
                ('footer_description', models.TextField(default='Leading the digital transformation journey of the Union Territory of Puducherry.')),
                ('web_information_manager', models.CharField(default='Shri. Aman Sharma', max_length=200)),
                ('web_information_manager_designation', models.CharField(default='Director of Information Technology', max_length=200)),
                ('web_information_manager_email', models.EmailField(default='directorit@py.gov.in', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
