# Generated by Django 6.0.5 on 2026-06-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Anchor id used by the card, e.g. 'notifications', 'tenders', 'rti', 'eodb', 'downloads'", unique=True)),
                ('eyebrow', models.CharField(help_text="Small label above title, e.g. 'Updates'", max_length=60)),
                ('title', models.CharField(help_text="e.g. 'Notifications & Alerts'", max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('bell', 'Bell / Notifications'), ('download', 'Download'), ('briefcase', 'Briefcase / EoDB'), ('gavel', 'Gavel / RTI'), ('tender', 'Tender / Contract')], default='bell', max_length=20)),
                ('accent', models.CharField(default='#7C3AED', max_length=20)),
                ('surface', models.CharField(default='rgba(124,58,237,0.12)', max_length=50)),
                ('href', models.CharField(default='#documents', help_text="Where the card's button links to", max_length=200)),
                ('cta', models.CharField(default='Open', help_text="Button text, e.g. 'Open updates'", max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Citizen Resource Card',
                'verbose_name_plural': 'Citizen Resource Cards (Notifications/Tenders/RTI/EoDB)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portal_settings.resourcegroup')),
            ],
            options={
                'verbose_name': 'Resource Card Point',
                'verbose_name_plural': 'Resource Card Points',
                'ordering': ['order'],
            },
        ),
    ]
