# Generated by Django 6.0.5 on 2026-06-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_settings', '0002_resourcegroup_resourcepoint'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='portalstat',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site',
            field=models.OneToOneField(blank=True, help_text='The website these settings belong to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitesetting', to='sites.site'),
        ),
    ]
