# Generated by Django 6.0.5 on 2026-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_settings', '0003_official_site_partner_site_portalstat_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='overview_description',
            field=models.TextField(blank=True, default='', help_text='Paragraph shown in the Department Overview section on the homepage.'),
        ),
    ]
