# Generated by Django 6.0.5 on 2026-06-25 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_settings', '0004_add_overview_description'),
        ('sites', '0004_add_footer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Public Grievance Redressal'", max_length=100)),
                ('href', models.CharField(default='#', max_length=300)),
                ('icon', models.CharField(choices=[('gavel', 'Gavel / Grievance'), ('clipboard', 'Clipboard / Track'), ('bell', 'Bell / Notifications'), ('download', 'Download / Circulars'), ('briefcase', 'Briefcase / Tenders'), ('users', 'Users / Helpdesk'), ('link', 'Generic Link')], default='link', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Footer Citizen Service Link',
                'verbose_name_plural': 'Footer — Citizen Service Links',
                'ordering': ['order'],
            },
        ),
    ]
