# Generated by Django 6.0.5 on 2026-06-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Short unique id used by the frontend's VITE_SITE_KEY, e.g. 'dit', 'health', 'tourism'. Lowercase, no spaces.", unique=True)),
                ('name', models.CharField(help_text="Human-friendly name shown in admin, e.g. 'Directorate of IT' or 'Health Department'", max_length=200)),
                ('template', models.CharField(choices=[('dit-portal', 'DIT Portal (default government template)'), ('template-two', 'Template Two'), ('template-three', 'Template Three')], default='dit-portal', help_text='Which React template/theme this website uses. You choose this as the developer.', max_length=50)),
                ('domain', models.CharField(blank=True, help_text="Optional: the live domain for this site, e.g. 'health.py.gov.in' (informational)", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="If a request doesn't specify a site, this site is used. Keep exactly one default.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Website (Site)',
                'verbose_name_plural': 'Websites (Sites)',
                'ordering': ['name'],
            },
        ),
    ]
