# Generated by Django 6.0.5 on 2026-06-02 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites', models.ManyToManyField(blank=True, help_text='Sites this user can manage. Superusers ignore this — they always see everything.', related_name='admins', to='sites.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Admin',
                'verbose_name_plural': 'Site Admins',
            },
        ),
    ]
