# Generated by Django 6.0.5 on 2026-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_siteadminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='template',
            field=models.CharField(choices=[('template-one', 'Template One — DIT Portal (Blue)'), ('template-two', 'Template Two — EDU Portal (Green)'), ('template-three', 'Template Three — Finance Portal (Red)')], default='template-one', help_text='Which React template/theme this website uses. You choose this as the developer.', max_length=50),
        ),
    ]
