# Generated by Django 6.0.5 on 2026-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='template',
            field=models.CharField(choices=[('template-one', 'Template One — DIT Portal (Blue)')], default='template-one', help_text='Which React template/theme this website uses. You choose this as the developer.', max_length=50),
        ),
    ]
