# Generated by Django 6.0.5 on 2026-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('template', 'Template'), ('form', 'Form'), ('guideline', 'Guideline'), ('report', 'Report'), ('circular', 'Circular'), ('other', 'Other')], default='template', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload PDF, DOCX, XLSX, or other file', upload_to='downloads/')),
                ('file_size_display', models.CharField(blank=True, help_text="Human-readable size shown to users, e.g. '2.4 MB'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
