# Generated by Django 6.0.5 on 2026-06-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_add_footer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-friendly id. Used in the menu href as '#page-<slug>', e.g. 'transport-schedule'.", max_length=100)),
                ('title', models.CharField(help_text='Page heading shown at the top.', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Page body. You can paste HTML — tables, links, lists, headings, etc. Example: <table><tr><th>Route</th></tr><tr><td>Route 1</td></tr></table>')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['order', 'title'],
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
