const defaultContent = {
  site: {
    departmentName: '',
    governmentName: '',
    helpdeskEmail: '',
    helpdeskEmailDisplay: '',
    phone: '',
    phoneCompact: '',
    officeName: '',
    lastUpdated: '',
    contentOwner: '',
    webInformationManager: '',
    webInformationManagerDesignation: '',
    webInformationManagerEmail: '',
    webInformationManagerEmailDisplay: '',
    address: '',
    overviewDescription: '',
    footerDescription: '',
  },
  newsItems:      [],
  heroSlides:     [],
  homeHighlights: [],
  portalStats:    [],
  quickLinks:     [],
  officials:      [],
  services:       [],
  activities:     [],
  resourceGroups: [],
  footerLinks:    [],
  documents:      [],
  downloads:      [],
  notifications:  [],
  partners:       [],
  about:          null,
};

export default defaultContent;
