const defaultContent = {
  site: {
    departmentName: 'Directorate of Information Technology',
    governmentName: 'Government of Puducherry',
    helpdeskEmail: 'directorit@py.gov.in',
    helpdeskEmailDisplay: 'directorit[at]py[dot]gov[dot]in',
    phone: '+91-413-2246090',
    phoneCompact: '+914132246090',
    officeName: 'Directorate Of Information Technology',
    lastUpdated: '29 May 2026',
    contentOwner: 'Directorate of Information Technology, Government of Puducherry',
    webInformationManager: 'Shri. Aman Sharma',
    webInformationManagerDesignation: 'Director of Information Technology',
    webInformationManagerEmail: 'directorit@py.gov.in',
    webInformationManagerEmailDisplay: 'directorit[at]py[dot]gov[dot]in',
    address:
      'II Floor, Planning & Research Department Complex, 505, Kamaraj Salai, Sakthi Nagar, Saram, Puducherry, 605013',
    footerDescription:
      'Leading the digital transformation journey of the Union Territory of Puducherry. We are committed to fostering an innovative ecosystem that empowers citizens and streamlines governance through technology.',
  },
  newsItems: [
    'Purchase and AMC - Guidelines issued on 11 Feb 2024',
    'PSWAN (State Wide Area Network) implementation status updated',
    'Upcoming Cybersecurity Workshop for State Officers - March 15',
    'New CSC (Common Services Centres) Registration Template available for download',
    'E-District modernization projects underway for enhanced citizen services',
  ],
  heroSlides: [
    {
      id: 'hero-technology',
      imageKey: 'hero1',
      kicker: 'DIRECTORATE OF IT',
      title: 'Empowering Puducherry Through Technology',
      description:
        'Providing state-of-the-art IT infrastructure and e-governance services for a seamless digital future.',
      primaryCta: 'Explore Services',
      primaryHref: '#services',
      secondaryCta: 'Learn More',
      secondaryHref: '#about-detail',
      variant: 'danger',
    },
    {
      id: 'hero-csc',
      imageKey: 'hero2',
      kicker: 'COMMON SERVICES',
      title: 'Bridging the Digital Divide',
      description:
        'Ensuring government services are accessible to every citizen via Common Services Centres across the state.',
      primaryCta: 'Find a CSC',
      primaryHref: '#services',
      secondaryCta: '',
      secondaryHref: '',
      variant: 'primary',
    },
  ],
  homeHighlights: [
    {
      icon: 'citizen',
      title: 'Citizen Services',
      description: 'Single-window access points for digital government services and support.',
      href: '#services',
    },
    {
      icon: 'schemes',
      title: 'Schemes & Programs',
      description: 'Digital India, CSC, PSWAN, and e-Governance program information.',
      href: '#activities',
    },
    {
      icon: 'circulars',
      title: 'Circulars / Orders',
      description: 'Official guidelines, orders, templates, and policy documents.',
      href: '#documents',
    },
    {
      icon: 'tenders',
      title: 'Tenders',
      description: 'Procurement references and eTendering access for vendors and departments.',
      href: '#tenders',
    },
    {
      icon: 'infrastructure',
      title: 'IT Infrastructure',
      description: 'PSWAN, State Data Centre, cloud hosting, and network enablement services.',
      href: '#services',
    },
    {
      icon: 'helpdesk',
      title: 'Helpdesk Support',
      description: 'Assistance for service access, technical queries, grievances, and follow-up.',
      href: '#grievances',
    },
  ],
  portalStats: [
    { value: '24x7', label: 'Digital access' },
    { value: '6', label: 'Core IT services' },
    { value: '1', label: 'Unified resource hub' },
  ],
  quickLinks: [
    {
      label: 'Services',
      caption: 'Citizen-facing digital services',
      icon: 'laptop',
      href: '#services',
      accent: '#3B82F6',
      surface: 'rgba(59, 130, 246, 0.12)',
    },
    {
      label: 'Documents',
      caption: 'Policies, templates and guidelines',
      icon: 'fileInvoice',
      href: '#documents',
      accent: '#4F46E5',
      surface: 'rgba(79, 70, 229, 0.12)',
    },
    {
      label: 'Notifications',
      caption: 'Latest departmental announcements',
      icon: 'bullhorn',
      href: '#notifications',
      accent: '#7C3AED',
      surface: 'rgba(124, 58, 237, 0.12)',
    },
    {
      label: 'Downloads',
      caption: 'Forms, circulars and official assets',
      icon: 'download',
      href: '#downloads',
      accent: '#10B981',
      surface: 'rgba(16, 185, 129, 0.12)',
    },
  ],
  officials: [
    {
      name: 'Shri. K. LAKSHMINARAYANAN',
      role: "Hon'ble Minister for Information Technology",
      imageKey: 'minister',
      initials: 'KL',
    },
    {
      name: 'Shri Choudhary Mohammed Yasin, I.A.S.',
      role: 'Secretary to Government (IT)',
      imageKey: 'secretary',
      initials: 'CMY',
    },
    {
      name: 'Shri. Aman Sharma',
      role: 'Director of Information Technology',
      imageKey: 'director',
      initials: 'AS',
    },
  ],
  services: [
    {
      icon: 'network',
      accent: '#3B82F6',
      surface: 'rgba(59,130,246,0.12)',
      title: 'PSWAN (State Wide Area Network)',
      desc: 'High-speed network connectivity linking all government departments across the Union Territory.',
      links: [
        { label: 'Learn more', href: '#services-detail' },
        { label: 'Apply', href: '#contact' },
      ],
    },
    {
      icon: 'server',
      accent: '#4F46E5',
      surface: 'rgba(79,70,229,0.12)',
      title: 'State Data Centre (SDC)',
      desc: 'Centralized hosting and cloud infrastructure providing secure data storage and disaster recovery.',
      links: [
        { label: 'Cloud Services', href: '#services-detail' },
        { label: 'Guidelines', href: '#documents' },
      ],
    },
    {
      icon: 'users',
      accent: '#10B981',
      surface: 'rgba(16,185,129,0.12)',
      title: 'Common Services Centres',
      desc: 'One-stop shop for G2C services, ensuring digital empowerment for citizens at the grassroot level.',
      links: [
        { label: 'Find a CSC', href: '#services-detail' },
        { label: 'Register', href: '#contact' },
      ],
    },
    {
      icon: 'portal',
      accent: '#7C3AED',
      surface: 'rgba(124,58,237,0.12)',
      title: 'Government Portals & Applications',
      desc: 'Design, development, and maintenance support for official portals, applications, and online service workflows.',
      links: [
        { label: 'Portal support', href: '#services-detail' },
        { label: 'Request help', href: '#contact' },
      ],
    },
    {
      icon: 'shield',
      accent: '#4F46E5',
      surface: 'rgba(79,70,229,0.12)',
      title: 'Cybersecurity & Data Governance',
      desc: 'Policy, advisory, and implementation support for secure government systems, data management, and resilience.',
      links: [
        { label: 'Security services', href: '#services-detail' },
        { label: 'Guidelines', href: '#documents' },
      ],
    },
    {
      icon: 'training',
      accent: '#10B981',
      surface: 'rgba(16,185,129,0.12)',
      title: 'Capacity Building & IT Consultancy',
      desc: 'Technical consultancy, digital skill development, and project support for departmental digitization initiatives.',
      links: [
        { label: 'Training support', href: '#services-detail' },
        { label: 'Contact DIT', href: '#contact' },
      ],
    },
  ],
  activities: [
    {
      title: 'Schemes & Programs',
      color: 'primary',
      icon: 'lightbulb',
      items: ['Digital India coordination', 'PSWAN implementation', 'State Data Centre projects', 'E-District modernization'],
    },
    {
      title: 'Circulars & Orders',
      color: 'success',
      icon: 'running',
      items: ['G.O.s / Notifications', 'Orders & Circulars', 'Purchase and AMC guidelines', 'Committee minutes'],
    },
    {
      title: 'Latest News & Tenders',
      color: 'danger',
      icon: 'newspaper',
      items: ['Latest guidelines', 'New templates', 'eProcurement notices', 'Annual reports'],
    },
  ],
  resourceGroups: [
    {
      id: 'notifications',
      eyebrow: 'Updates',
      title: 'Notifications & Alerts',
      description:
        'Track circulars, advisory notices, workshop announcements, and service updates released by the department.',
      icon: 'bell',
      accent: '#7C3AED',
      surface: 'rgba(124, 58, 237, 0.12)',
      points: ['Latest circulars', 'System advisories', 'Department announcements'],
      href: '#documents',
      cta: 'Open updates',
    },
    {
      id: 'downloads',
      eyebrow: 'Resources',
      title: 'Downloads Hub',
      description:
        'Access templates, guidelines, forms, and official documents prepared for departments, vendors, and citizens.',
      icon: 'download',
      accent: '#10B981',
      surface: 'rgba(16, 185, 129, 0.12)',
      points: ['Application templates', 'Guideline documents', 'Reference forms'],
      href: '#documents',
      cta: 'View downloads',
    },
    {
      id: 'tenders',
      eyebrow: 'Procurement',
      title: 'Tenders',
      description:
        'Access procurement notices, eTendering references, and tender-related document support for IT initiatives.',
      icon: 'tender',
      accent: '#10B981',
      surface: 'rgba(16, 185, 129, 0.12)',
      points: ['eTendering links', 'Vendor notices', 'Procurement documents'],
      href: '#documents',
      cta: 'Open tender resources',
    },
    {
      id: 'eodb',
      eyebrow: 'Business',
      title: 'Ease of Doing Business',
      description:
        'Quick access to digital facilitation touchpoints that support departmental services and business-facing processes.',
      icon: 'briefcase',
      accent: '#3B82F6',
      surface: 'rgba(59, 130, 246, 0.12)',
      points: ['Service enablement', 'Workflow simplification', 'Digital access points'],
      href: '#services',
      cta: 'Explore services',
    },
    {
      id: 'rti',
      eyebrow: 'Transparency',
      title: 'Right to Information',
      description:
        'Find the relevant information area for citizen communication, contact details, and document-led transparency flows.',
      icon: 'gavel',
      accent: '#4F46E5',
      surface: 'rgba(79, 70, 229, 0.12)',
      points: ['Citizen contact flow', 'Document references', 'Public information support'],
      href: '#contact',
      cta: 'Contact the office',
    },
  ],
  documents: [
    {
      id: 1,
      title: 'Purchase and AMC - Guidelines 2024',
      category: 'Guidelines',
      desc: 'Standard operating procedures for IT procurement and annual maintenance.',
      type: 'PDF',
      meta: '2.4 MB',
    },
    {
      id: 2,
      title: 'PSWAN Connectivity Implementation Order',
      category: 'Orders',
      desc: 'Official order mandating connectivity for all block-level offices.',
      type: 'PDF',
      meta: '1.1 MB',
    },
    {
      id: 3,
      title: 'CSC Registration Template v2.1',
      category: 'Templates',
      desc: 'Updated application format for new Common Service Centre aspirants.',
      type: 'DOCX',
      meta: '128 KB',
    },
    {
      id: 4,
      title: 'State IT Policy - 2024 (Official)',
      category: 'Guidelines',
      desc: 'Comprehensive roadmap for digital transformation in Puducherry.',
      type: 'PDF',
      meta: '1.8 MB',
    },
    {
      id: 5,
      title: 'Digital Literacy Campaign Report',
      category: 'Reports',
      desc: 'Annual assessment of digital empowerment initiatives in the state.',
      type: 'PDF',
      meta: '3.2 MB',
    },
    {
      id: 6,
      title: 'Software Procurement Circular',
      category: 'Orders',
      desc: 'Guidelines for departments on purchasing licensed software.',
      type: 'PDF',
      meta: '0.9 MB',
    },
    {
      id: 7,
      title: 'IT Procurement Tender Reference',
      category: 'Tenders',
      desc: 'Tender reference entry for IT procurement notices and eProcurement access.',
      type: 'PDF',
      meta: '760 KB',
    },
  ],
};

export default defaultContent;
