# Generated by Django 6.0.5 on 2026-06-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_alter_site_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="Column heading, e.g. 'Quick Links'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Footer Link Group',
                'verbose_name_plural': 'Footer Link Groups (Finance)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('href', models.CharField(default='#', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='finance_content.footerlinkgroup')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Section heading, e.g. 'BEAMS User Manual'", max_length=200)),
                ('icon', models.CharField(choices=[('Bell', 'Bell / Notifications'), ('Briefcase', 'Briefcase / Resources'), ('BookOpen', 'Book / Documents'), ('Link2', 'Link / Useful Links'), ('FileText', 'File / Guidelines'), ('Shield', 'Shield / Compliance')], default='Bell', max_length=30)),
                ('color', models.CharField(default='var(--primary)', help_text='CSS color for the icon/heading strip', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site')),
            ],
            options={
                'verbose_name': 'Info Section',
                'verbose_name_plural': 'Info Sections (Finance)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('href', models.CharField(blank=True, default='#', help_text='Optional link for this item', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance_content.infosection')),
            ],
            options={
                'verbose_name': 'Info Item',
                'verbose_name_plural': 'Info Items',
                'ordering': ['order'],
            },
        ),
    ]
