# Generated by Django 6.0.5 on 2026-06-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Which website this item belongs to. Leave blank to use the default site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='sites.site'),
        ),
    ]
